
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Init
    before: |
      mkdir EnoLandingPageBackend/data
      cp EnoLandingPageBackend/appsettings.example.json EnoLandingPageBackend/appsettings.Development.json
      cd EnoLandingPageBackend/ClientApp
      npm install
      npm build
  - name: Frontend
    command: |
      cd EnoLandingPageBackend/ClientApp
      npm start
  - name: Backend
    command: |
      cd EnoLandingPageBackend
      dotnet watch run
    openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5001
    onOpen: open-preview
  - port: 4200

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - angular.ng-template
    - esbenp.prettier-vscode
