version: '3.7'
services:
  enoportal:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./sessions:/root/.aspnet/DataProtection-Keys
      # For the Database
      - ./data:/app/data
      # For the Scoreboard (just at the moment)
      - ./enginedata:/app/enginedata
      # For Scoreboard and AttackInfo (if they are not supplied via the HTTP Endpoint)
      - ./scoreboard:/app/wwwroot/scoreboard
    # volumes:
    #   - ./EnoLandingPageBackend/appsettings.Development.json:/app/appsettings.json
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.rule=Host(`enowars.aquiver.de`)'
      - 'traefik.http.routers.whoami.entrypoints=websecure'
      - 'traefik.http.routers.whoami.tls.certresolver=myresolver'
    ports:
      - 8080:80
#   traefik:
#     image: 'traefik:v2.4'
#     container_name: 'traefik'
#     command:
#       #- "--log.level=DEBUG"
#       - '--api.insecure=true'
#       - '--providers.docker=true'
#       - '--providers.docker.exposedbydefault=false'
#       - '--entrypoints.websecure.address=:443'
#       - '--entrypoints.web.address=:80'
#       - --entrypoints.web.http.redirections.entrypoint.to=websecure
#       - --entrypoints.web.http.redirections.entrypoint.scheme=https
#       - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
#       #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
#       - '--certificatesresolvers.myresolver.acme.email=daniel-habenicht@outlook.de'
#       - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
#     ports:
#       - '80:80'
#       - '443:443'
#       - '8080:8080'
#     volumes:
#       - './letsencrypt:/letsencrypt'
#       - '/var/run/docker.sock:/var/run/docker.sock:ro'
