version: '3'

services:
  enolandingpage:
    build: .
    environment:
      - "EnoLandingPage__Title=FoobarCTF"
      - "EnoLandingPage__StartTime=2020-11-22T15:00:00Z"
      - "EnoLandingPage__RegistrationCloseOffset=48"
      - "EnoLandingPage__CheckInBeginOffset=12"
      - "EnoLandingPage__CheckInEndOffset=2"
      - "EnoLandingPage__HetznerVulnboxType=cx11"
      - "EnoLandingPage__HetznerCloudApiToken=HHw7idPPxG7qX7Yq5c577475ov0fpnHadlqqJeUm3MphPl9di5JsGDsoq7zfbEcL"
      - "EnoLandingPage__HetznerVulnboxImage=ubuntu-20.04"
      - "EnoLandingPage__HetznerVulnboxPubkey=bambissh"
      - "EnoLandingPage__HetznerVulnboxLocation=fsn1"
      - "EnoLandingPage__OAuthClientId=1043"
      - "EnoLandingPage__OAuthClientSecret=8fa93a6a0571e05522eda6982bab9557300ba8bb59a931b274dcf2381728592c"
    ports:
      - "5001:80"
    volumes:
      - ./data:/app/data
